version: "3.8"

services:
  # Backend service (renamed to ocr-api)
  ocr-api:
    build:
      context: . # Since docker-compose.yml is in the backend folder
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app
    ports:
      - "4000:4000" # Expose backend on port 4000
    environment:
      NODE_ENV: development
    command: npm start
    networks:
      - app-network

  # Frontend service
  frontend:
    build:
      context: ../node_ocr_fe # Relative path to the frontend folder
      dockerfile: Dockerfile.dev
    volumes:
      - ../node_ocr_fe:/usr/src/app
    ports:
      - "3001:3000" # Expose frontend on port 3001
    environment:
      - WATCHPACK_POLLING=true
    networks:
      - app-network
    depends_on:
      - ocr-api # Ensure backend starts before frontend

# Define a shared network for the services to communicate
networks:
  app-network:
    driver: bridge
